#This playbbok will install HTTP server and start the server.
---
- hosts: appServers
  become: true
  tasks:
    - name: Install Apache HTTP server
      yum: name=httpd update_cache=yes state=latest
    - name: Start HTTP Server
      service: name=httpd enabled=yes state=started
    - name: Insert Index Page
      template:
       src: index.html
       dest: /var/www/html/index.html
---
# for ubuntu
- hosts: all
  become: true
  tasks:
    - name: Install Apache server
      apt: name=apache2 update_cache=yes state=latest
    - name: Start apache2
      service: name=apache2 enabled=yes state=started
    - name: Insert index page
      template:
        src: /home/ubuntu/index.html
        dest: /var/www/html/index.html


...
